name: BiblioPlusBack
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Cambiado a 'temurin' para Java 17
          java-version: '17' 

      - name: Build with Maven
        run: mvn clean install

      - name: Package application
        run: mvn package